// Code generated by build.sh . DO NOT EDIT.

package proto
import (
_ "github.com/erda-project/erda-proto-go/pipeline/pb"
_ "github.com/erda-project/erda-proto-go/oap/metrics/pb"
_ "github.com/erda-project/erda-proto-go/oap/trace/pb"
_ "github.com/erda-project/erda-proto-go/oap/entity/pb"
)